import type { Product, Testimonial, Category, CartItemWithProduct, OrderWithItems } from "@shared/schema";

// Categories
export const categories: Category[] = [
  {
    id: "1",
    name: "Necklaces",
    slug: "necklaces",
    description: "Elegant necklaces for every occasion",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop",
  },
  {
    id: "2",
    name: "Rings",
    slug: "rings",
    description: "Timeless rings that speak volumes",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=600&fit=crop",
  },
  {
    id: "3",
    name: "Earrings",
    slug: "earrings",
    description: "Stunning earrings to frame your face",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop",
  },
  {
    id: "4",
    name: "Bracelets",
    slug: "bracelets",
    description: "Graceful bracelets for your wrist",
    imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop",
  },
  {
    id: "5",
    name: "Bangles",
    slug: "bangles",
    description: "Traditional bangles with modern flair",
    imageUrl: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600&h=600&fit=crop",
  },
  {
    id: "6",
    name: "Anklets",
    slug: "anklets",
    description: "Delicate anklets for subtle elegance",
    imageUrl: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
  },
];

// Products
export const products: Product[] = [
  {
    id: "1",
    name: "Golden Serpent Necklace",
    description: "A stunning 22K gold necklace featuring an intricate serpent design with ruby eyes. Perfect for special occasions.",
    price: 2499,
    originalPrice: 2999,
    category: "necklaces",
    material: "22K Gold",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 128,
  },
  {
    id: "2",
    name: "Diamond Solitaire Ring",
    description: "Classic diamond solitaire ring set in 18K white gold. A timeless symbol of eternal love.",
    price: 3999,
    originalPrice: null,
    category: "rings",
    material: "18K White Gold",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: true,
    isBestSeller: false,
    rating: 5.0,
    reviewCount: 89,
  },
  {
    id: "3",
    name: "Pearl Drop Earrings",
    description: "Elegant freshwater pearl drop earrings with delicate gold chain. Perfect for everyday luxury.",
    price: 899,
    originalPrice: 1099,
    category: "earrings",
    material: "14K Gold",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: false,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 245,
  },
  {
    id: "4",
    name: "Rose Gold Tennis Bracelet",
    description: "Stunning tennis bracelet featuring brilliant-cut diamonds set in rose gold.",
    price: 4599,
    originalPrice: 5299,
    category: "bracelets",
    material: "18K Rose Gold",
    imageUrl: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 167,
  },
  {
    id: "5",
    name: "Traditional Gold Bangles Set",
    description: "Set of 6 traditional gold bangles with intricate filigree work. Perfect for celebrations.",
    price: 5999,
    originalPrice: null,
    category: "bangles",
    material: "22K Gold",
    imageUrl: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 92,
  },
  {
    id: "6",
    name: "Dainty Gold Anklet",
    description: "Delicate gold chain anklet with tiny charm accents. Subtle elegance for your ankle.",
    price: 399,
    originalPrice: 499,
    category: "anklets",
    material: "14K Gold",
    imageUrl: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 78,
  },
  {
    id: "7",
    name: "Emerald Statement Necklace",
    description: "Luxurious statement necklace featuring Colombian emeralds set in 18K gold.",
    price: 8999,
    originalPrice: 9999,
    category: "necklaces",
    material: "18K Gold",
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: true,
    isBestSeller: false,
    rating: 5.0,
    reviewCount: 34,
  },
  {
    id: "8",
    name: "Vintage Ruby Ring",
    description: "Art deco inspired ruby ring with diamond halo setting in platinum.",
    price: 6499,
    originalPrice: null,
    category: "rings",
    material: "Platinum",
    imageUrl: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 56,
  },
  {
    id: "9",
    name: "Sapphire Stud Earrings",
    description: "Classic blue sapphire studs surrounded by a halo of diamonds.",
    price: 2799,
    originalPrice: 3199,
    category: "earrings",
    material: "18K White Gold",
    imageUrl: "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: true,
    isBestSeller: false,
    rating: 4.8,
    reviewCount: 112,
  },
  {
    id: "10",
    name: "Charm Link Bracelet",
    description: "Customizable charm bracelet with gold links. Add your own story.",
    price: 1299,
    originalPrice: null,
    category: "bracelets",
    material: "14K Gold",
    imageUrl: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 198,
  },
  {
    id: "11",
    name: "Diamond Eternity Band",
    description: "Full eternity band with round brilliant diamonds. Symbol of endless love.",
    price: 3299,
    originalPrice: 3799,
    category: "rings",
    material: "18K Gold",
    imageUrl: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: "12",
    name: "Layered Gold Necklace Set",
    description: "Set of three delicate gold chains of varying lengths. Modern layered look.",
    price: 1599,
    originalPrice: 1899,
    category: "necklaces",
    material: "14K Gold",
    imageUrl: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    images: [],
    inStock: true,
    isTrending: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 143,
  },
];

// Testimonials
export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Priya Sharma",
    initials: "PS",
    rating: 5,
    text: "The craftsmanship is absolutely exquisite! I purchased the Golden Serpent Necklace for my wedding anniversary and it exceeded all expectations. The attention to detail is remarkable.",
    productCategory: "Necklaces",
  },
  {
    id: "2",
    name: "Ananya Reddy",
    initials: "AR",
    rating: 5,
    text: "Elorie Elegance has become my go-to for all special occasions. The Diamond Solitaire Ring my husband bought me is stunning. Their customer service is exceptional too!",
    productCategory: "Rings",
  },
  {
    id: "3",
    name: "Meera Patel",
    initials: "MP",
    rating: 5,
    text: "I've been a loyal customer for years. Every piece I own from Elorie Elegance receives countless compliments. The quality is consistent and the designs are timeless.",
    productCategory: "Earrings",
  },
  {
    id: "4",
    name: "Kavitha Nair",
    initials: "KN",
    rating: 5,
    text: "The Traditional Gold Bangles Set I ordered for my daughter's wedding was perfect. The filigree work is intricate and beautiful. Worth every penny!",
    productCategory: "Bangles",
  },
  {
    id: "5",
    name: "Deepa Krishnan",
    initials: "DK",
    rating: 5,
    text: "Fast shipping, beautiful packaging, and the Rose Gold Tennis Bracelet is even more gorgeous in person. Elorie Elegance truly understands luxury.",
    productCategory: "Bracelets",
  },
  {
    id: "6",
    name: "Lakshmi Venkat",
    initials: "LV",
    rating: 5,
    text: "Bought the Pearl Drop Earrings as a gift for my mother. She was overjoyed! The pearls have a beautiful luster and the gold setting is delicate yet sturdy.",
    productCategory: "Earrings",
  },
];

// Sample cart data
export const sampleCart: CartItemWithProduct[] = [
  {
    id: "cart-1",
    userId: "user-1",
    productId: "1",
    quantity: 1,
    product: products[0],
  },
  {
    id: "cart-2",
    userId: "user-1",
    productId: "3",
    quantity: 2,
    product: products[2],
  },
];

// Sample orders
export const sampleOrders: OrderWithItems[] = [
  {
    id: "ORD-2024-001",
    userId: "user-1",
    status: "delivered",
    totalAmount: 3398,
    shippingAddress: "123 Golden Lane, Mumbai, Maharashtra 400001",
    trackingNumber: "EE2024001IN",
    createdAt: new Date("2024-12-15"),
    items: [
      {
        id: "oi-1",
        orderId: "ORD-2024-001",
        productId: "1",
        quantity: 1,
        price: 2499,
        product: products[0],
      },
      {
        id: "oi-2",
        orderId: "ORD-2024-001",
        productId: "3",
        quantity: 1,
        price: 899,
        product: products[2],
      },
    ],
  },
  {
    id: "ORD-2024-002",
    userId: "user-1",
    status: "shipped",
    totalAmount: 4599,
    shippingAddress: "456 Diamond Street, Delhi 110001",
    trackingNumber: "EE2024002IN",
    createdAt: new Date("2024-12-20"),
    items: [
      {
        id: "oi-3",
        orderId: "ORD-2024-002",
        productId: "4",
        quantity: 1,
        price: 4599,
        product: products[3],
      },
    ],
  },
  {
    id: "ORD-2024-003",
    userId: "user-1",
    status: "processing",
    totalAmount: 6499,
    shippingAddress: "789 Pearl Avenue, Bangalore 560001",
    trackingNumber: null,
    createdAt: new Date("2024-12-22"),
    items: [
      {
        id: "oi-4",
        orderId: "ORD-2024-003",
        productId: "8",
        quantity: 1,
        price: 6499,
        product: products[7],
      },
    ],
  },
];

// Helper functions
export function getTrendingProducts(): Product[] {
  return products.filter((p) => p.isTrending);
}

export function getBestSellers(): Product[] {
  return products.filter((p) => p.isBestSeller);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}
